spring:
  application:
    name: "user-service"


server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true

logging:
  level:
    org:
      springframework:
        boot:
          web: DEBUG
      apache:
        catalina: INFO


env_variables:
  JWT_SECRET: "EbrahimMohamed-1EbrahimMohamed-1123456789"
  JWT_EXPIRATION_MS: "3600000"